/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author unity
 */
public class GerenciamentoLivros extends javax.swing.JFrame {

    /**
     * Creates new form LivrosTela
     */
    public GerenciamentoLivros() {
        super ("Livros");
        initComponents();
        buscarLivros();
        setLocationRelativeTo(null);   
    }
  private void buscarLivros (){
 try{
 Livros [] livros = LivroNotaDAO();
 livrosComboBox.setModel(new DefaultComboBoxModel<>(livros));
 }
 catch (Exception e){
 JOptionPane.showMessageDialog(null, "Livros indisponíveis, tente novamente mais tarde.");
    }
 }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        livrosPanel = new javax.swing.JPanel();
        idLivroTextField = new javax.swing.JTextField();
        nomeLivroTextField = new javax.swing.JTextField();
        autorLivroTextField = new javax.swing.JTextField();
        editoraLivroTextField = new javax.swing.JTextField();
        paginasLivroTextField = new javax.swing.JTextField();
        adicionarLivroButton = new javax.swing.JButton();
        atualizarLivroButton = new javax.swing.JButton();
        removerLivroButton = new javax.swing.JButton();
        cancelarLivroButton = new javax.swing.JButton();
        generoLivroTextField1 = new javax.swing.JTextField();
        livrosComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        livrosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciamento de Livros"));

        idLivroTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        idLivroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idLivroTextFieldActionPerformed(evt);
            }
        });

        nomeLivroTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        autorLivroTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Autor"));

        editoraLivroTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Editora"));
        editoraLivroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editoraLivroTextFieldActionPerformed(evt);
            }
        });

        paginasLivroTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de Páginas"));

        adicionarLivroButton.setText("Novo");

        atualizarLivroButton.setText("Atualizar");

        removerLivroButton.setText("Remover");

        cancelarLivroButton.setText("Cancelar");

        generoLivroTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gênero"));
        generoLivroTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoLivroTextField1ActionPerformed(evt);
            }
        });

        livrosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout livrosPanelLayout = new javax.swing.GroupLayout(livrosPanel);
        livrosPanel.setLayout(livrosPanelLayout);
        livrosPanelLayout.setHorizontalGroup(
            livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livrosPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idLivroTextField)
                    .addComponent(nomeLivroTextField)
                    .addComponent(autorLivroTextField)
                    .addComponent(editoraLivroTextField)
                    .addComponent(paginasLivroTextField)
                    .addComponent(generoLivroTextField1)
                    .addGroup(livrosPanelLayout.createSequentialGroup()
                        .addGroup(livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adicionarLivroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removerLivroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarLivroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atualizarLivroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(livrosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        livrosPanelLayout.setVerticalGroup(
            livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livrosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(livrosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idLivroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomeLivroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(autorLivroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editoraLivroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generoLivroTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paginasLivroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarLivroButton)
                    .addComponent(atualizarLivroButton))
                .addGap(18, 18, 18)
                .addGroup(livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarLivroButton)
                    .addComponent(removerLivroButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(livrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(livrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idLivroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idLivroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idLivroTextFieldActionPerformed

    private void editoraLivroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editoraLivroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editoraLivroTextFieldActionPerformed

    private void generoLivroTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoLivroTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoLivroTextField1ActionPerformed

    private void livrosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_livrosComboBoxActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarLivroButton;
    private javax.swing.JButton atualizarLivroButton;
    private javax.swing.JTextField autorLivroTextField;
    private javax.swing.JButton cancelarLivroButton;
    private javax.swing.JTextField editoraLivroTextField;
    private javax.swing.JTextField generoLivroTextField1;
    private javax.swing.JTextField idLivroTextField;
    private javax.swing.JComboBox<Livros> livrosComboBox;
    private javax.swing.JPanel livrosPanel;
    private javax.swing.JTextField nomeLivroTextField;
    private javax.swing.JTextField paginasLivroTextField;
    private javax.swing.JButton removerLivroButton;
    // End of variables declaration//GEN-END:variables

    private Livros[] LivroNotaDAO() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
